import { useMemo,useState } from 'react';import { FiCheck,FiSend } from 'react-icons/fi';
const suggestions=['오늘 일정 알려줘','이번 주 할 일 알려줘','최근 회의 정리해줘','마감 임박 업무 알려줘'];
const formatAgentText=(value='')=>{const text=String(value).replace(/\*\*/g,'').replace(/^#{1,6}\s*/gm,'').replace(/^\s*-\s*/gm,'').trim();const fields={};text.split('\n').forEach((line)=>{const match=line.match(/^(회의명|회의 제목|날짜|참석자|내용|요약|태그|주요 내용)\s*:\s*(.+)$/);if(match)fields[match[1]]=match[2].trim()});const title=fields['회의명']||fields['회의 제목'];return title?`최근 회의를 정리해 드릴게요.\n\n📌 ${title}\n🗓️ ${fields['날짜']||'날짜 정보 없음'}  ·  👥 ${fields['참석자']||'참석자 정보 없음'}\n\n핵심 내용\n${fields['요약']||fields['내용']||fields['주요 내용']||'요약 내용이 없습니다.'}`:text};
function Proposal({action,busy,onApprove}){const schedule=action.type==='schedule';const payload=action.payload||{};return <section className="agent-proposal"><em>{schedule?'일정 제안':'할 일 제안'}</em><strong>{payload.title||'제목 없음'}</strong><p>{schedule?`${payload.date||'날짜 미정'} · ${payload.time||'시간 미정'}`:`${payload.assignee||'담당자 미정'} · ${payload.due||'마감일 미정'}`}</p>{payload.description&&<small>{payload.description}</small>}<button className="agent-approval" type="button" onClick={()=>onApprove(action)} disabled={busy}><FiCheck/>{schedule?'캘린더에 추가':'할 일에 추가'}</button></section>}
export default function AiAgentChat({onSend,onAddEvent,onAddTask,events=[],tasks=[],meetings=[]}){
 const[message,setMessage]=useState('');const[messages,setMessages]=useState([]);const[sending,setSending]=useState(false);const[confirming,setConfirming]=useState(null);
 const briefing=useMemo(()=>{const now=new Date();const key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;const today=events.filter((item)=>item.date===key);const open=tasks.filter((item)=>item.status!=='DONE');return `${today.length?`오늘 ${today.map((item)=>`${item.time} ${item.title}`).join(', ')} 일정이 있어요.`:'오늘 일정은 없어요.'} 진행할 업무는 ${open.length}건이에요. ${meetings[0]?`최근 ‘${meetings[0].title}’ 회의도 확인해 보세요.`:''}`},[events,tasks,meetings]);
 const submit=async(event)=>{event.preventDefault();const question=message.trim();if(!question||sending)return;setMessages((list)=>[...list,{role:'user',text:question}]);setMessage('');setSending(true);try{const history=messages.map((item)=>({role:item.role==='agent'?'assistant':'user',content:item.text}));const result=await onSend(question,history);setMessages((list)=>[...list,{role:'agent',text:result.answer,actions:result.proposedActions||[]}])}catch(error){const detail=error.code==='ECONNABORTED'?'AI 응답 시간이 길어지고 있습니다. 잠시 후 다시 시도해 주세요.':error.response?.data?.detail||error.message||'AI 연결에 실패했습니다.';setMessages((list)=>[...list,{role:'agent',text:detail}])}finally{setSending(false)}};
 const approve=async(action)=>{setConfirming(action);try{action.type==='schedule'?await onAddEvent(action.payload):await onAddTask({...action.payload,status:'TODO'});setMessages((list)=>[...list,{role:'agent',text:action.type==='schedule'?'일정을 캘린더에 추가했어요.':'업무를 할 일에 추가했어요.'}])}finally{setConfirming(null)}};
 return <article className="dashboard-card agent-card"><div className="agent-title"><span className="dog-avatar">🐶</span><div><h2>AI 업무 비서</h2><p><i/> 일정·업무·회의를 함께 확인해요</p></div></div><div className="agent-conversation">{messages.length?messages.map((item,index)=><div className={`chat-bubble ${item.role}`} key={index}><p>{formatAgentText(item.text)}</p>{item.actions?.length>0&&<div className="agent-proposals">{item.actions.map((action,actionIndex)=><Proposal key={actionIndex} action={action} busy={confirming===action} onApprove={approve}/>)}</div>}</div>):<div className="agent-message dog-briefing"><span>🐾</span><p><strong>오늘 업무를 브리핑해 드릴게요.</strong>{briefing}</p></div>}{sending&&<div className="chat-bubble agent loading">답변을 준비하고 있어요…</div>}</div><div className="suggestion-list">{suggestions.map((item)=><button type="button" key={item} onClick={()=>setMessage(item)}>{item}<span>›</span></button>)}</div><form className="agent-input" onSubmit={submit}><input value={message} onChange={(event)=>setMessage(event.target.value)} placeholder="메시지를 입력하세요..."/><button disabled={sending||!message.trim()}><FiSend/></button></form><small className="mock-note">AI 제안은 확인 후 저장됩니다</small></article>
}
