import { useMemo,useState } from 'react';
import { FiCalendar,FiChevronLeft,FiChevronRight,FiEdit2,FiPlus,FiTrash2 } from 'react-icons/fi';
import DashboardModal from './DashboardModal';

const toDateKey=(date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const fromDateKey=(value)=>{const[year,month,day]=value.split('-').map(Number);return new Date(year,month-1,day)};
const monthCells=(viewMonth)=>{
 const first=new Date(viewMonth.getFullYear(),viewMonth.getMonth(),1);
 const start=new Date(first);start.setDate(first.getDate()-first.getDay());
 return Array.from({length:42},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return date});
};

export default function DashboardCalendar({events,selectedDate,onSelectDate,selectedEvents,onAdd,onUpdate,onDelete}){
 const[viewMonth,setViewMonth]=useState(()=>{const date=fromDateKey(selectedDate);return new Date(date.getFullYear(),date.getMonth(),1)});
 const[editing,setEditing]=useState(null);const[deleting,setDeleting]=useState(null);const[saving,setSaving]=useState(false);
 const cells=useMemo(()=>monthCells(viewMonth),[viewMonth]);
 const moveMonth=(amount)=>setViewMonth((current)=>new Date(current.getFullYear(),current.getMonth()+amount,1));
 const selectDay=(date)=>{onSelectDate(toDateKey(date));if(date.getMonth()!==viewMonth.getMonth()||date.getFullYear()!==viewMonth.getFullYear())setViewMonth(new Date(date.getFullYear(),date.getMonth(),1))};
 const goToday=()=>{const today=new Date();setViewMonth(new Date(today.getFullYear(),today.getMonth(),1));onSelectDate(toDateKey(today))};
 const submit=async(event)=>{event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget);const values={title:form.get('title'),description:form.get('description'),date:form.get('date'),time:form.get('time'),end_time:form.get('end_time')};try{if(editing?.id)await onUpdate(editing.id,values);else await onAdd(values);const date=fromDateKey(values.date);setViewMonth(new Date(date.getFullYear(),date.getMonth(),1));setEditing(null)}finally{setSaving(false)}};
 const remove=async()=>{setSaving(true);try{await onDelete(deleting.id);setDeleting(null)}finally{setSaving(false)}};
 return <><article className="dashboard-card calendar-card"><div className="card-heading"><div><span className="card-icon"><FiCalendar/></span><div><h2>캘린더</h2><p>일정에서 업무 흐름을 확인하세요.</p></div></div><button className="icon-button" type="button" aria-label="일정 추가" onClick={()=>setEditing({date:selectedDate,time:'09:00',end_time:'10:00'})}><FiPlus/></button></div><div className="calendar-toolbar"><h3>{viewMonth.getFullYear()}년 {viewMonth.getMonth()+1}월</h3><div><button type="button" onClick={()=>moveMonth(-1)} aria-label="이전 달"><FiChevronLeft/></button><button type="button" onClick={goToday}>오늘</button><button type="button" onClick={()=>moveMonth(1)} aria-label="다음 달"><FiChevronRight/></button></div></div><div className="calendar-weekdays">{['일','월','화','수','목','금','토'].map((day)=><span key={day}>{day}</span>)}</div><div className="calendar-days">{cells.map((date)=>{const key=toDateKey(date);const event=events.find((item)=>item.date===key);const muted=date.getMonth()!==viewMonth.getMonth();return <button type="button" key={key} className={`${selectedDate===key?'selected':''} ${muted?'muted':''}`} onClick={()=>selectDay(date)}><span>{date.getDate()}</span>{event&&<i className={event.tone} title={event.title}/>}</button>})}</div><div className="selected-schedule"><span>{selectedDate.slice(5).replace('-','.')}</span><div className="schedule-items">{selectedEvents.length?selectedEvents.map((item)=><p key={item.id}><b>{item.time}</b><span>{item.title}</span><button type="button" onClick={()=>setEditing(item)} aria-label="일정 수정"><FiEdit2/></button><button type="button" onClick={()=>setDeleting(item)} aria-label="일정 삭제"><FiTrash2/></button></p>):<p className="empty-event">등록된 일정이 없습니다.</p>}</div></div></article>{editing&&<DashboardModal title={editing.id?'일정 수정':'일정 추가'} onClose={()=>setEditing(null)}><form className="dashboard-form" onSubmit={submit}><label>일정 제목<input name="title" required defaultValue={editing.title||''} autoFocus/></label><label>설명<input name="description" defaultValue={editing.description||''}/></label><div><label>날짜<input name="date" type="date" required defaultValue={editing.date}/></label><label>시작 시간<input name="time" type="time" required defaultValue={editing.time}/></label></div><label>종료 시간<input name="end_time" type="time" required defaultValue={editing.end_time||''}/></label><footer><button type="button" onClick={()=>setEditing(null)}>취소</button><button className="primary-button" disabled={saving}>{saving?'저장 중...':'저장'}</button></footer></form></DashboardModal>}{deleting&&<DashboardModal title="일정 삭제" onClose={()=>setDeleting(null)}><div className="delete-confirm"><p>‘{deleting.title}’ 일정을 삭제할까요?</p><footer><button type="button" onClick={()=>setDeleting(null)}>취소</button><button type="button" className="danger-button" onClick={remove} disabled={saving}>삭제</button></footer></div></DashboardModal>}</>
}
