import { useEffect, useState } from 'react';
import { FiArrowRight, FiCheck, FiEdit2, FiFileText, FiPlus, FiShare2, FiTrash2, FiUsers, FiX, FiZap } from 'react-icons/fi';
import { deleteMeetingShare, extractMeetingActions, getMeetingInvitations, getMeetingShares, getParticipantSuggestions, inviteMeetingShare, respondMeetingInvitation } from '../../features/dashboardService';
import DashboardModal from './DashboardModal';

export default function RecentMeetings({ meetings, selectedMeeting, onSelectMeeting, onAdd, onUpdate, onDelete, onAddTask, onAddEvent }) {
  const [showAll, setShowAll] = useState(false), [detail, setDetail] = useState(null), [editing, setEditing] = useState(null), [deleting, setDeleting] = useState(null), [extraction, setExtraction] = useState(null);
  const [sharing, setSharing] = useState(null), [shares, setShares] = useState([]), [invitations, setInvitations] = useState([]), [suggestions, setSuggestions] = useState([]), [shareError, setShareError] = useState(''), [saving, setSaving] = useState(false);
  const [selectedParticipants, setSelectedParticipants] = useState([]), [participantQuery, setParticipantQuery] = useState('');
  useEffect(() => { getMeetingInvitations().then(setInvitations).catch(() => {}); }, []);
  const openDetail = (item) => { setDetail(item); onSelectMeeting(item); };
  const meetingAt = (item) => item.date ? `${item.date.replaceAll('.', '-')}T14:00` : `${new Date().toISOString().slice(0, 10)}T14:00`;
  const submit = async (event) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const values = { title: form.get('title'), meetingAt: form.get('meetingAt'), participants: form.get('participants').split(',').map((v) => v.trim()).filter(Boolean), participantUserIds: editing.id ? undefined : selectedParticipants.map((item) => item.id), summary: form.get('summary'), content: form.get('content'), status: form.get('status') }; try { editing.id ? await onUpdate(editing.id, values) : await onAdd(values); setEditing(null); setSelectedParticipants([]); setParticipantQuery(''); } finally { setSaving(false); } };
  const beginCreate = async () => { setSelectedParticipants([]); setParticipantQuery(''); setSuggestions(await getParticipantSuggestions('')); setEditing({ status: 'DRAFT' }); };
  const searchForCreate = (value) => { setParticipantQuery(value); getParticipantSuggestions(value.replace(/^@/, '')).then(setSuggestions).catch(() => setSuggestions([])); };
  const selectParticipant = (item) => { setSelectedParticipants((list) => list.some((value) => value.id === item.id) ? list : [...list, item]); setParticipantQuery(''); };
  const analyze = async (item) => { setSaving(true); try { setExtraction({ meeting: item, ...await extractMeetingActions(item.id) }); setDetail(null); } finally { setSaving(false); } };
  const accept = async (type, item) => { setSaving(true); try { if (type === 'task') await onAddTask({ ...item, status: 'TODO' }); else await onAddEvent(item); setExtraction((old) => ({ ...old, [type === 'task' ? 'tasks' : 'schedules']: old[type === 'task' ? 'tasks' : 'schedules'].filter((value) => value !== item) })); } finally { setSaving(false); } };
  const remove = async () => { setSaving(true); try { await onDelete(deleting.id); setDeleting(null); } finally { setSaving(false); } };
  const beginEdit = async (meeting) => { setShareError(''); setEditing(meeting); setDetail(null); setShares([]); try { const [shared, users] = await Promise.all([getMeetingShares(meeting.id), getParticipantSuggestions('')]); setShares(shared); setSuggestions(users); } catch (error) { setShareError(error.response?.data?.detail || '공유 참여자 목록을 불러오지 못했습니다. 회의록 내용은 계속 수정할 수 있습니다.'); } };
  const invite = async (event) => { event.preventDefault(); setSaving(true); setShareError(''); const form = new FormData(event.currentTarget); try { const share = await inviteMeetingShare(editing.id, { email: form.get('email'), permission: form.get('permission') }); setShares((list) => [share, ...list.filter((item) => item.userId !== share.userId)]); event.currentTarget.reset(); } catch (error) { setShareError(error.response?.data?.detail || '참여자를 추가하지 못했습니다.'); } finally { setSaving(false); } };
  const respond = async (item, status) => { setSaving(true); try { await respondMeetingInvitation(item.meetingId, status); setInvitations((list) => list.filter((value) => value.id !== item.id)); if (status === 'ACCEPTED') window.location.reload(); } finally { setSaving(false); } };
  const shareManager = editing?.id && editing.canDelete ? <><div className="sharing-section-title"><strong>공유 참여자 관리</strong><span>추가, 권한 변경, 공유 취소를 할 수 있습니다.</span></div><form className="meeting-share-form" onSubmit={invite}><label>참여자<input name="email" type="email" list="participant-suggestions" required placeholder="@이름 또는 이메일" onChange={(event) => getParticipantSuggestions(event.target.value.replace(/^@/, '')).then(setSuggestions).catch(() => setSuggestions([]))} /><datalist id="participant-suggestions">{suggestions.map((item) => <option key={item.id} value={item.email}>@{item.name}</option>)}</datalist></label><label>권한<select name="permission"><option value="VIEWER">열람만 가능</option><option value="EDITOR">편집 가능</option></select></label><button className="primary-button" disabled={saving}><FiShare2 /> 추가</button>{shareError && <p className="share-error">{shareError}</p>}</form><div className="meeting-share-list">{shares.map((item) => <section key={item.id}><div><strong>@{item.displayName}</strong><p>{item.email} · {item.permission === 'EDITOR' ? '편집 가능' : '열람 전용'} · {item.status === 'PENDING' ? '수락 대기' : item.status === 'ACCEPTED' ? '공유 중' : '거절됨'}</p></div><button className="share-remove" type="button" onClick={async () => { await deleteMeetingShare(editing.id, item.id); setShares((list) => list.filter((value) => value.id !== item.id)); }}><FiTrash2 /> 삭제</button></section>)}{!shares.length && <p className="empty-tasks">공유 중인 참여자가 없습니다.</p>}</div></> : null;

  return <>
    <article className="dashboard-card meetings-card"><div className="card-heading"><div><span className="card-icon"><FiFileText /></span><div><h2>최근 회의록</h2><p>회의에서 업무와 일정을 연결하세요.</p></div></div><div className="heading-actions">{invitations.length > 0 && <button className="text-button invitation-button" onClick={() => setSharing({ invitations: true })}>초대 {invitations.length}건</button>}<button className="text-button" onClick={() => setShowAll(true)}>전체 보기 <FiArrowRight /></button><button className="icon-button" onClick={beginCreate}><FiPlus /></button></div></div><div className="meeting-list">{meetings.slice(0, 5).map((item) => <button key={item.id} className={selectedMeeting?.id === item.id ? 'active' : ''} onClick={() => openDetail(item)}><div className="meeting-meta"><span>{item.date}</span><em>{item.tag}</em></div><h3>{item.title}</h3><p>{item.summary}</p><div className="meeting-footer"><span><FiUsers /> {item.participants}</span><b>회의록 보기 <FiArrowRight /></b></div></button>)}</div></article>
    {showAll && <DashboardModal title="전체 회의록" onClose={() => setShowAll(false)}><div className="all-meetings">{meetings.map((item) => <button key={item.id} onClick={() => { setShowAll(false); openDetail(item); }}><span>{item.date}</span><div><strong>{item.title}</strong><p>{item.summary}</p></div><em>{item.tag}</em></button>)}</div></DashboardModal>}
    {detail && <DashboardModal title={detail.title} description={`${detail.date} · ${detail.accessLevel === 'OWNER' ? '작성자' : detail.accessLevel === 'EDITOR' ? '편집 가능' : '열람 전용'}`} onClose={() => setDetail(null)}><div className="meeting-detail"><p><b>참석자</b>{detail.participants}</p><p><b>회의 요약</b>{detail.summary}</p>{detail.content && <p><b>회의 내용</b>{detail.content}</p>}<div className="detail-actions"><button className="agent-analyze-button" onClick={() => analyze(detail)} disabled={saving}><FiZap /> AI 업무·일정 추출</button>{detail.canEdit && <button className="primary-button" onClick={() => beginEdit(detail)}><FiEdit2 /> 수정</button>}{detail.canDelete && <button className="danger-button" onClick={() => { setDeleting(detail); setDetail(null); }}><FiTrash2 /> 삭제</button>}</div></div></DashboardModal>}
    {editing && <DashboardModal title={editing.id ? '회의록 수정' : '회의록 추가'} onClose={() => setEditing(null)}><form className="dashboard-form" onSubmit={submit}><label>회의 제목<input name="title" required defaultValue={editing.title || ''} /></label><div><label>회의 일시<input name="meetingAt" type="datetime-local" required defaultValue={meetingAt(editing)} /></label><label>상태<select name="status" defaultValue={editing.status || 'DRAFT'}><option value="DRAFT">작성 중</option><option value="CONFIRMED">확정</option><option value="ARCHIVED">보관</option></select></label></div>{!editing.id && <div className="participant-picker"><label>함께 볼 참여자<input value={participantQuery} onChange={(event) => searchForCreate(event.target.value)} placeholder="@이름으로 검색" /></label>{participantQuery && <div className="participant-results">{suggestions.filter((item) => !selectedParticipants.some((value) => value.id === item.id)).map((item) => <button type="button" key={item.id} onClick={() => selectParticipant(item)}><strong>@{item.name}</strong><span>{item.email}</span></button>)}</div>}<div className="participant-chips">{selectedParticipants.map((item) => <button type="button" key={item.id} onClick={() => setSelectedParticipants((list) => list.filter((value) => value.id !== item.id))}>@{item.name} <FiX /></button>)}</div><small>선택한 사내 사용자는 생성 즉시 회의록을 열람할 수 있습니다.</small></div>}<label>참석자 메모<input name="participants" defaultValue={editing.participants || ''} placeholder="계정이 없는 외부 참석자 등" /></label><label>요약<textarea name="summary" rows="3" defaultValue={editing.summary || ''} /></label><label>회의 내용<textarea name="content" rows="6" defaultValue={editing.content || ''} /></label><footer><button type="button" onClick={() => setEditing(null)}>취소</button><button className="primary-button" disabled={saving}>저장</button></footer></form>{shareManager}</DashboardModal>}
    {extraction && <DashboardModal title="AI가 발견한 항목" description={extraction.meeting.title} onClose={() => setExtraction(null)}><div className="extraction-results">{extraction.tasks.map((item, index) => <section key={`task-${index}`}><em>할 일</em><strong>{item.title}</strong><p>{item.assignee || '담당자 미정'} · {item.due || '마감일 미정'}</p><button onClick={() => accept('task', item)} disabled={saving}>할 일에 추가</button></section>)}{extraction.schedules.map((item, index) => <section key={`schedule-${index}`}><em>일정</em><strong>{item.title}</strong><p>{item.date} {item.time}</p><button onClick={() => accept('schedule', item)} disabled={saving}>캘린더에 추가</button></section>)}</div></DashboardModal>}
    {deleting && <DashboardModal title="회의록 삭제" onClose={() => setDeleting(null)}><div className="delete-confirm"><p>‘{deleting.title}’ 회의록을 삭제할까요?</p><footer><button onClick={() => setDeleting(null)}>취소</button><button className="danger-button" onClick={remove}>삭제</button></footer></div></DashboardModal>}
    {sharing?.invitations && <DashboardModal title="받은 회의록 초대" onClose={() => setSharing(null)}><div className="meeting-share-list">{invitations.map((item) => <section key={item.id}><div><strong>{item.displayName}</strong><p>{item.email} · {item.permission === 'EDITOR' ? '편집 가능' : '열람 전용'}</p></div><button onClick={() => respond(item, 'ACCEPTED')} disabled={saving}><FiCheck /> 수락</button><button onClick={() => respond(item, 'DECLINED')} disabled={saving}><FiX /> 거절</button></section>)}</div></DashboardModal>}
  </>;
}
