import { useState } from 'react';
import { FiCheckSquare,FiEdit2,FiPlus,FiTrash2 } from 'react-icons/fi';
import DashboardModal from './DashboardModal';
const labels={ALL:'전체',TODO:'할 일',IN_PROGRESS:'진행 중',DONE:'완료'};
export default function TaskList({tasks,filter,onFilter,selectedMeeting,onAdd,onUpdate,onDelete}){
 const[editing,setEditing]=useState(null);const[deleting,setDeleting]=useState(null);const[saving,setSaving]=useState(false);const visible=tasks.filter((task)=>(filter==='ALL'||task.status===filter)&&(!selectedMeeting||selectedMeeting.taskIds.includes(task.id)));
 const submit=async(event)=>{event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget);const values={title:form.get('title'),assignee:form.get('assignee'),due:form.get('due'),status:form.get('status'),priority:form.get('priority'),description:form.get('description')};try{if(editing?.id)await onUpdate(editing.id,values);else await onAdd(values);setEditing(null)}finally{setSaving(false)}};
 const remove=async()=>{setSaving(true);try{await onDelete(deleting.id);setDeleting(null)}finally{setSaving(false)}};
 const dueValue=(due)=>due&&due.length===5?`2026-${due.replace('.','-')}`:due||'2026-08-29';
 return <><article className="dashboard-card task-card" id="dashboard-tasks"><div className="card-heading"><div><span className="card-icon"><FiCheckSquare/></span><div><h2>Action Items</h2><p>{selectedMeeting?`‘${selectedMeeting.title}’에서 이어진 업무`:'회의와 연결된 업무 진행 현황'}</p></div></div><button className="primary-button" type="button" onClick={()=>setEditing({status:'TODO',priority:'NORMAL'})}><FiPlus/> 할 일 추가</button></div><div className="task-filters">{Object.entries(labels).map(([key,label])=><button type="button" key={key} className={filter===key?'active':''} onClick={()=>onFilter(key)}>{label}</button>)}</div><div className="task-table"><div className="task-head"><span>업무</span><span>담당자</span><span>마감일</span><span>상태</span><span>관리</span></div>{visible.map((task)=><div className="task-row" key={task.id}><strong>{task.title}{task.urgent&&<small>마감 임박</small>}</strong><span>{task.assignee}</span><span>{task.due||'-'}</span><span><em className={`status-${task.status.toLowerCase()}`}>{labels[task.status]}</em></span><span className="row-actions"><button type="button" onClick={()=>setEditing(task)} aria-label="할 일 수정"><FiEdit2/></button><button type="button" onClick={()=>setDeleting(task)} aria-label="할 일 삭제"><FiTrash2/></button></span></div>)}{!visible.length&&<p className="empty-tasks">조건에 맞는 업무가 없습니다.</p>}</div></article>{editing&&<DashboardModal title={editing.id?'할 일 수정':'할 일 추가'} onClose={()=>setEditing(null)}><form className="dashboard-form" onSubmit={submit}><label>업무 제목<input name="title" required defaultValue={editing.title||''} autoFocus/></label><label>설명<input name="description" defaultValue={editing.description||''}/></label><div><label>담당자<input name="assignee" required defaultValue={editing.assignee||''}/></label><label>마감일<input name="due" type="date" defaultValue={dueValue(editing.due)}/></label></div><div><label>상태<select name="status" defaultValue={editing.status||'TODO'}><option value="TODO">할 일</option><option value="IN_PROGRESS">진행 중</option><option value="DONE">완료</option></select></label><label>우선순위<select name="priority" defaultValue={editing.priority||'NORMAL'}><option value="LOW">낮음</option><option value="NORMAL">보통</option><option value="HIGH">높음</option></select></label></div><footer><button type="button" onClick={()=>setEditing(null)}>취소</button><button className="primary-button" disabled={saving}>{saving?'저장 중...':'저장'}</button></footer></form></DashboardModal>}{deleting&&<DashboardModal title="할 일 삭제" onClose={()=>setDeleting(null)}><div className="delete-confirm"><p>‘{deleting.title}’ 업무를 삭제할까요?</p><footer><button type="button" onClick={()=>setDeleting(null)}>취소</button><button type="button" className="danger-button" onClick={remove} disabled={saving}>삭제</button></footer></div></DashboardModal>}</>
}
